Starting coarse data cProcessing year: 1950
Processing year: 1951
Processing year: 1952
Processing year: 1953
Processing year: 1954
Processing year: 1955
Processing year: 1956
Processing year: 1957
ogram took 163.1067 seconds
Processing year: 1952
Importing 12 files
Calculating pv mean
2024-11-26 10:46:19,567 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home/yannickh00/.local/lib/python3.11/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nosplit_nbytes_bin = await stream.read_bytes(fmt_size)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/yannickh00/.local/lib/python3.11/site-packages/distributed/worker.py", line 1250, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yannickh00/.local/lib/python3.11/site-packages/distributed/utils_comm.py", line 461, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
  File "/home/yannickh00/.local/lib/python3.11/site-packages/distributed/utils_comm.py", line 440, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home/yannickh00/.local/lib/python3.11/site-packages/distributed/core.py", line 1256, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yannickh00/.local/lib/python3.11/site-packages/distributed/core.py", line 1015, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yannickh00/.local/lib/python3.11/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
  File "/home/yannickh00/.local/lib/python3.11/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://127.0.0.1:59022 remote=tcp://127.0.0.1:39501>: Stream is closed
Program took 159.0018 seconds
Processing year: 1953
Importing 12 files
Calculating pv mean
Program took 175.2957 seconds
Processing year: 1954
Importing 12 files
Calculating pv mean
Program took 161.4146 seconds
Processing year: 1955
Importing 12 files
Calculating pv mean
Program took 160.6809 seconds
Processing year: 1956
Importing 12 files
Calculating pv mean
Program took 171.8715 seconds
Processing year: 1957
Importing 12 files
Calculating pv mean
